config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # sidekiq web ui monitoring
  # FIXME: scope to admin user only
  require 'sidekiq/web'
  if Rails.env.production?
    authenticate :admin_user, lambda { |u| u.administrator? } do
      mount Sidekiq::Web => '/admin/sidekiq'
    end
  else
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :user, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification'
  }

  devise_scope :user do
    # student registration routes
    get 'student/register' => 'devise_extentions/student#new'
    post 'student/register' => 'devise_extentions/student#create'
    # mentor registration routes
    get 'mentor/register' => 'devise_extentions/mentor#new'
    post 'mentor/register' => 'devise_extentions/mentor#create'
  end

  resources :careers, only: [:index]
  resources :contacts, only: [:index]
  resources :dashboard, only: [:index]
  resources :landing, only: [:index]
  resources :services, only: [:index]
  resources :scholastics, only: [:index] do
    collection do
      get 'universities'
      get 'languages'
      get 'majors'
      get 'countries'
      get 'timezones'
      get 'search_tags'
    end
  end

  resources :mentors, only: [:index] do
    get 'search', on: :collection
    resources :bookmark, only: [:create, :destroy]
    member do
      post :notify_student
    end
  end

  resources :students, only: [:index] do
    get 'search', on: :collection
  end

  resources :profile, except: [:index, :destroy, :create, :new] do
    member do
      get 'mentors'
      get 'students'
      get 'account_settings'
      put 'primary_photo'
      match 'private_message', via: [:get, :post]
    end

    resources :recommendations, only: [:create]
    resources :dashboard, only: [:index]
    resources :messenger, only: [:show] do
      post :message
      get :video_call
      put :decline_video_call
    end

    resources :mentors, only: [:update] do
      put 'account_settings', on: :member
    end

    resources :students, only: [:update] do
      put 'account_settings', on: :member
    end

    resources :orders, only: [:index, :new, :create, :show] do
      member do
        put :instruction
        put :comment
        put :accept
        put :confirm
        put :in_progress
        put :completed
        put :decline
        put :cancel
        put :close
      end
    end

    resources :tasks, only: [:show, :update] do
      member do
        get :upload_request_file
        put :upload_request_file
        get :upload_revised_file
        put :upload_revised_file
        put :in_progress
        put :done
        put :completed
        put :instruction
        put :comment
        get :appointment
        put :appointment
      end

      resources :ratings
    end

    resources :appointments, except: [:destroy, :update] do
      member do
        put :decline
        put :confirm
        put :cancel
      end

      collection do
        post :request_schedule
      end
    end

    resources :schedules do
      member do
        put :close
      end

      get :checker, on: :collection
    end

    resources :images, only: [:index, :create, :destroy] do
      put :set_as_primary_photo, on: :member
    end

    resources :documents, only: [:index, :create, :destroy]
    resources :notifications, only: [:index]
    resources :transactions do
      post :hook, on: :member
    end

    resources :wallets
    resources :schools, only: [:create, :update, :destroy]
    resources :videos, only: [:create, :destroy]
    resources :alternative_contacts, only: [:create, :update, :destroy]
  end

  root 'landing#index'
end

app/models/messenger.rb
# == Schema Information
#
# Table name: messengers
#
#  id         :integer          not null, primary key
#  task_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string(255)
#

class Messenger < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:history]
  include UniqueFriendlyId

  belongs_to :task
  has_many :messages, dependent: :destroy
  has_many :messenger_participants, dependent: :destroy
  has_one :appointment, through: :task

  validates :task, presence: true
end

app/controllers/messenger_controller.rb
class MessengerController < ApplicationController
  before_filter :set_profile
  before_filter :set_messenger
  before_filter :authorize_resource!

  def video_call
    load_messages
    close_concurrent_opened_browser
    notify_video_call_participants
  end

  def decline_video_call
    decline_video_call_notification

    respond_to do |format|
      format.js
    end
  end

  def show
    if params[:video] == '1'
      flash[:info] = 'Only one browser | browser tab can have a video call for each task messenger session.'
    end

    load_messages
  end

  def message
    @message = Message.new(sanitize_params)
    @message.valid?
    @message.save

    if @message.errors.empty?
      Fiber.new do
        WebsocketRails[:messenger].trigger 'new', {
          message: {
            id: @message.id,
            content: render_to_string(@message),
            object: @message.attributes,
            messenger_id: @message.messenger.slug,
            user_id: @message.user.id
          }
        }
      end.resume
    end
  end

  private

  def authorize_resource!
    authorize @messenger.present? ? @messenger : :messenger
  end

  def close_concurrent_opened_browser
    Fiber.new do
      WebsocketRails[:messenger].trigger 'initialize_video_call', {
        messenger: {
          id: @messenger.id,
          messenger_id: @messenger.slug,
          user_id: @profile.id
        }
      }
    end.resume
  end

  def decline_video_call_notification
    if params[:from_user]
      from_user = User.find params[:from_user]
      Fiber.new do
        WebsocketRails[:messenger].trigger 'decline_video_call', {
          messenger: {
            id: @messenger.id,
            content: render_to_string('_request_video_call_modal', locals: { user: from_user, messenger: @messenger, from_user: @profile }, layout: false),
            object: @messenger.attributes,
            messenger_id: @messenger.slug,
            user_id: from_user.id
          }
        }
      end.resume
    end
  end

  def notify_video_call_participants
    user_participants = @messenger.messenger_participants.map(&:user)
    user_participants.reject!{ |user| user.id == @profile.id }

    user_participants.each do |user|
      Fiber.new do
        WebsocketRails[:messenger].trigger 'video_call', {
          messenger: {
            id: @messenger.id,
            content: render_to_string('_video_call_notification_modal', locals: { user: user, messenger: @messenger, from_user: @profile }, layout: false),
            object: @messenger.attributes,
            messenger_id: @messenger.slug,
            user_id: user.id
          }
        }
      end.resume
    end
  end

  def set_messenger
    @messenger = Messenger.find(params[:messenger_id] || params[:id])
  end

  def sanitize_params
    params.require(:message).permit([:messenger_id, :user_id, :text])
  end

  def load_messages
    @page = params[:page].nil? ? 1 : params[:page].to_i
    @messages = @messenger.messages.page(@page)
    @messages = @messages.reverse

    if params[:auto] == '1'
      flash[:info] = 'Your session has started. You can start the chat session.'
    end

    respond_to do |format|
      format.html do
        @message = @messenger.messages.new
        @message.user = @profile
      end
      format.js
    end
  end
end

app/helpers/messenger_helper.rb
module MessengerHelper
end

app/views/messenger/_countdown_timer.html.slim
.row
  .col-sm-12
    .alert.alert-info
      p Your session is not yet starting please wait for the time.
.messenger-countdown-timer id="messenger-countdown-timer-#{@messenger.slug}" data-current-path=request.path data-remaining-time=@messenger.appointment.schedule.start_datetime_remaining

app/views/messenger/_form.html.slim
- if @messenger.appointment.approved?
  = simple_form_for(@message, html: { class: 'col-md-12 messenger-message-form' }, url: profile_messenger_message_path(@profile, @messenger), remote: true, method: :post) do |f|
    = f.hidden_field :messenger_id
    = f.hidden_field :user_id
    = f.input :text, as: :text, input_html: { placeholder: 'Write a message...', autofocus: true }, label: false
    - unless ['video_call', 'voice_call'].include? params[:action]
      / INITIATE VIDEO CALL
      - if params[:action] != 'video_call' && !current_user.administrator?
        = link_to 'Video Call', profile_messenger_video_call_path(@profile, @messenger), class: 'btn btn-warning btn-sm btn-flat', data: { no_turbolink: true }
    - if params[:action] == 'video_call' && !current_user.administrator?
      = link_to 'End Call ', profile_messenger_path(@profile, @messenger), class: 'btn btn-danger btn-sm btn-flat', data: { no_turbolink: true }
      = link_to 'Call Again', profile_messenger_video_call_path(@profile, @messenger), class: 'btn btn-warning btn-sm btn-flat mL10', data: { no_turbolink: true }
    = link_to t('views.tasks.view_task_label'), profile_task_path(@profile, @messenger.task), class: 'btn btn-default btn-sm btn-flat mL10'
    = f.submit t('views.labels.send'), class: 'btn btn-flat btn-blue pull-right btn-sm', data: { disable_with: t('views.labels.sending') }

app/views/messenger/_load_more_button.html.slim
= button_to t('views.labels.load_more'), profile_messenger_path(@profile, @messenger, page: @page + 1, format: :js), method: :get, remote: true, class: 'btn btn-blue btn-sm', data: { disable_with: t('views.labels.loading')}

app/views/messenger/_messenger_detail.html.slim
.row.profile-messages id="messenger-#{@messenger.id}-profile-#{@profile.id}"
  .col-sm-12
    .messages-scroll
      #load_more_messages.text-center
        = render 'load_more_button'
      .message-main-container
        .messages-container id=@messenger.slug
          = render @messages
      .scroll_end
  .col-sm-12
    .message-box
      = render 'form'

app/views/messenger/_request_video_call_modal.html.slim
.modal.fade.modal-default#request-video-call-notification-modal role='dialog' tabindex='-1' data-backdrop='static'
  .modal-dialog.default-position role='document'
    .modal-content
      .modal-header
        p
          strong Your call was declined.
      .modal-body
        p = " Do you want to call #{user.first_name} again?"
      .modal-footer
        .pull-left
          = link_to 'Cancel', profile_messenger_path(user, messenger), class: 'btn btn-default btn-sm btn-flat', data: { disable_with: t('views.labels.redirecting'), no_turbolink: true }
        .pull-right
          = link_to 'Video Call', profile_messenger_video_call_path(user, messenger), class: 'btn btn-success btn-sm btn-flat', data: { disable_with: 'Calling...', no_turbolink: true }

app/views/messenger/_video_call.html.slim
- if @messenger.appointment.approved?
  .video-holder id="video-call-#{@messenger.slug}" data-referer-path=profile_messenger_path(@profile, @messenger)
    .alert.alert-info
      p If you are in a call already and the connection is not established or having a bad connection, you can refresh the browser or click Call Again button below to refresh the peer connection.
    p.text-warning.peer-connection-state Calling...
    #responser_video.big_video
    .video-requester-holder
      video#requester_video.small_video oncontextmenu="return false;"
      meter.requester_volume min='-45' max='-20' high='-25' low='-40'
    hr

app/views/messenger/_video_call_notification_modal.html.slim
.modal.fade.modal-default#video-call-notification-modal role='dialog' tabindex='-1' data-backdrop='static'
  .modal-dialog.default-position role='document'
    .modal-content
      .modal-header
        p
          strong Video Call
      .modal-body
        p ="#{user.first_name} is calling you with a video call."
      .modal-footer
        .pull-left
          = button_to 'Decline', profile_messenger_decline_video_call_path(user, messenger, from_user: from_user.id, format: :js), method: :put, remote: true, class: 'btn btn-danger btn-sm btn-flat', data: { disable_with: t('views.labels.processing')}
        .pull-right
          = link_to 'Answer', profile_messenger_video_call_path(user, messenger), class: 'btn btn-success btn-sm btn-flat', data: { disable_with: 'Answering...' }

app/views/messenger/decline_video_call.js.erb
$('#video-call-notification-modal').modal('hide')
setTimeout(function() {
  $('#video-call-notification-modal').remove()
  $('.modal-backdrop').remove()
}, 300)

app/views/messenger/message.js.erb
<% if @message.errors.any? %>
  _n.renderErrorPopup("<%= @message.errors.full_messages.first %>")
<% end %>

app/views/messenger/show.html.slim
.container
  .profile.mT20
    .row
      = render 'profile/profile_sidebar'
      .col-sm-9
        #messenger-detail
          .box-panel.box-gray
            .box-inner
              h2.blue Mentor - Student Discussion room
              hr.white

              - if @messenger.appointment.schedule.start_appointment?(0)
                = render 'messenger_detail'
              - else
                = render 'countdown_timer'

app/views/messenger/show.js.erb
$('#load_more_messages').html('<%= escape_javascript(render "load_more_button") %>')
$('.messages-container').prepend('<%= escape_javascript(render @messages) %>')
$('time').timeago()

app/views/messenger/video_call.html.slim
.container
  .profile.mT20
    .row
      = render 'profile/profile_sidebar'
      .col-sm-9
        #messenger-detail
          .box-panel.box-gray
            .box-inner
              h2.blue Mentor - Student Discussion room
              hr.white

              - if @messenger.appointment.schedule.start_appointment?(0)
                = render 'video_call'
                = render 'messenger_detail'
              - else
                = render 'countdown_timer'