config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # sidekiq web ui monitoring
  # FIXME: scope to admin user only
  require 'sidekiq/web'
  if Rails.env.production?
    authenticate :admin_user, lambda { |u| u.administrator? } do
      mount Sidekiq::Web => '/admin/sidekiq'
    end
  else
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :user, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification'
  }

  devise_scope :user do
    # student registration routes
    get 'student/register' => 'devise_extentions/student#new'
    post 'student/register' => 'devise_extentions/student#create'
    # mentor registration routes
    get 'mentor/register' => 'devise_extentions/mentor#new'
    post 'mentor/register' => 'devise_extentions/mentor#create'
  end

  resources :careers, only: [:index]
  resources :contacts, only: [:index]
  resources :dashboard, only: [:index]
  resources :landing, only: [:index]
  resources :services, only: [:index]
  resources :scholastics, only: [:index] do
    collection do
      get 'universities'
      get 'languages'
      get 'majors'
      get 'countries'
      get 'timezones'
      get 'search_tags'
    end
  end

  resources :mentors, only: [:index] do
    get 'search', on: :collection
    resources :bookmark, only: [:create, :destroy]
    member do
      post :notify_student
    end
  end

  resources :students, only: [:index] do
    get 'search', on: :collection
  end

  resources :profile, except: [:index, :destroy, :create, :new] do
    member do
      get 'mentors'
      get 'students'
      get 'account_settings'
      put 'primary_photo'
      match 'private_message', via: [:get, :post]
    end

    resources :recommendations, only: [:create]
    resources :dashboard, only: [:index]
    resources :messenger, only: [:show] do
      post :message
      get :video_call
      put :decline_video_call
    end

    resources :mentors, only: [:update] do
      put 'account_settings', on: :member
    end

    resources :students, only: [:update] do
      put 'account_settings', on: :member
    end

    resources :orders, only: [:index, :new, :create, :show] do
      member do
        put :instruction
        put :comment
        put :accept
        put :confirm
        put :in_progress
        put :completed
        put :decline
        put :cancel
        put :close
      end
    end

    resources :tasks, only: [:show, :update] do
      member do
        get :upload_request_file
        put :upload_request_file
        get :upload_revised_file
        put :upload_revised_file
        put :in_progress
        put :done
        put :completed
        put :instruction
        put :comment
        get :appointment
        put :appointment
      end

      resources :ratings
    end

    resources :appointments, except: [:destroy, :update] do
      member do
        put :decline
        put :confirm
        put :cancel
      end

      collection do
        post :request_schedule
      end
    end

    resources :schedules do
      member do
        put :close
      end

      get :checker, on: :collection
    end

    resources :images, only: [:index, :create, :destroy] do
      put :set_as_primary_photo, on: :member
    end

    resources :documents, only: [:index, :create, :destroy]
    resources :notifications, only: [:index]
    resources :transactions do
      post :hook, on: :member
    end

    resources :wallets
    resources :schools, only: [:create, :update, :destroy]
    resources :videos, only: [:create, :destroy]
    resources :alternative_contacts, only: [:create, :update, :destroy]
  end

  root 'landing#index'
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index]
  before_filter :render_404_if_user_signed_in
  layout 'branding'

  def index
    @top_mentors = Mentor.top_nachers(1, 6)
  end

  private

  def render_404_if_user_signed_in
    if user_signed_in?
      render_404
    end
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/_banner.html.slim
.preview-banner style='background-image: url(#{image_url("banner.jpg")})'
  .container.white-overlay.black
    h2 BRILLIANCE BEYOND BORDERS
    h3 Find a mentor already studying your chosen
    h3 major at your dream university abroad!
    .black-box.col-lg-5.mT20
      p
        span For
        span.blue  only $5
        span  get personalized advice from
      p
        span one of our mentors for
        span.blue  30 minutes
      hr.white
      p
        span Give advice to future international
      p
        span student and
        span.blue  earn money!

      p.mT30
        small
          span Not ready to commit?
          span.blue  Learn more and receive updates!
      p
        span.blue.ion-help-circled
        span.blue.mT-10
          small  Got questions? Click here.

      .buttons.clearfix.mT20
        = link_to student_register_path, title: 'Student Sign Up', class: 'btn btn-blue btn-lg pull-left btn-bevel', data: { disable_with: t('views.labels.redirecting') } do
          span Student Sign Up
        = link_to mentor_register_path, title: 'Mentor Sign Up', class: 'btn btn-theme btn-lg pull-right btn-bevel', data: { disable_with: t('views.labels.redirecting') } do
          span Mentor Sign Up

app/views/landing/_branding.html.slim
.preview-branding
  .light-blue-background.pT40.pB30
    .container
      .row
        .col-sm-10.col-sm-offset-1
          .row
            .col-sm-6.text-center
              = image_tag('laptop.png')
            .col-sm-6.mT30
              .mL40
                h1 Because a friend can
                h1 take you a long way.

                .wordings
                  p.mT20.light-gray Through our online platform of mentors we offer
                  p.light-gray STUDENTS:

                  ul.mT10
                    li
                      p Contact with experienced mentors.
                    li
                      p Personalized advice on school selection.
                    li
                      p Application and CV editing / review.
                    li
                      p Scholarship and financial aid information.
                    li
                      p Campus tours.

                    p.light-gray.mT20 AND MORE!

app/views/landing/_coming_soon_mobile.html.slim
.preview-mobile
  .ocean-blue-background.pT60
    .container
      .row
        .col-sm-3.col-sm-offset-1
          = image_tag('mobile.png')
        .col-sm-7
          .col-sm-offset-1.col-sm-10.mB30
            h1.mB30 Coming Soon...
            h5 Our mobile app is currently under development.
            h5 Sign up today to receive instant updates!

app/views/landing/_login_modal.html.slim
.modal.fade.modal-default#login-modal role='dialog' tabindex='-1'
  .modal-dialog.default-position.modal-lg role='document'
    .modal-content
      .modal-body
        .clearfix
          = button_tag type: 'button', class: 'close', data: { dismiss: 'modal' } do
            span &times;
        .row.blue
          .col-sm-6
            h1 Login
            = simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
              .flash-message
              .form-inputs
                = f.input :username, autofocus: true
                = f.input :password
                .row
                  .col-sm-6
                    = f.input :remember_me, as: :boolean if devise_mapping.rememberable?
                  .col-sm-6
                    small
                      = link_to 'Forgot password?', new_password_path(resource_name), class: 'theme pull-right underline mR20 mT10'
              .form-actions
                .clearfix
                  = f.submit 'Log in', class: 'btn btn-blue btn-bevel pull-right pL30 pR30', data: { disable_with: t('views.labels.please_wait') }
          .col-sm-6.left-divider.pB30.mB20
            h2 Not Signed up?
            .row
              .col-sm-10.col-sm-offset-1.mT10
                p.text-center Get advice as a Student.
                = link_to 'Student Sign Up', student_register_path, class: 'btn btn-blue btn-block btn-bevel', data: { disable_with: t('views.labels.redirecting') }
              .col-sm-10.col-sm-offset-1.mT20
                p.text-center Get paid as a Mentor.
                = link_to 'Mentor Sign up', mentor_register_path, class: 'btn btn-theme btn-block btn-bevel', data: { disable_with: t('views.labels.redirecting') }
              .col-sm-10.col-sm-offset-1.mT60
                = link_to nil, class: 'theme' do
                  p.text-center.underline More Info

app/views/landing/_map.html.slim
.preview-map
  hr.sky-blue
  .theme-background.pT20
    .container
      .row
        .col-sm-offset-1.col-sm-11.mT10
          h2 Help map the path for students
          h2 abroad and get paid!
        .col-sm-offset-1.col-sm-10
          .col-sm-4.collapsable
            = image_tag('map.png')
          .col-sm-8.mT20
            p.light-gray Through our online platform MENTORS will be able to:
            ul.mT15
              li
                p Contact registered international students.
              li
                p Display their credentials with profile customization.
              li
                p View ratings and increase visibility through
                p ranking.
              li
                p Set prices for new tasks.

              p.light-gray.mT10 AND MORE!

app/views/landing/_quick_link.html.slim
.preview-quick-link
  .black-background
    .container
      h2 There's adventure abroad.
      h2 Take the next step and find a friend to guide you there!
      = link_to mentors_path, title: 'Find a friend abroad', class: 'btn btn-theme mT20', data: { disable_with: t('views.labels.redirecting') } do
        span FIND A FRIEND ABROAD

app/views/landing/_the_mentors.html.slim
.preview-the-mentors
  .container
    .row
      .col-sm-offset-1.col-sm-11
        h2.dark-green Give back. Earn fast.
  .container
    .row
      .col-sm-10.col-sm-offset-1
        .sky-blue-container
          .row
            / list
            .col-sm-5.mT15
              .traveler
                h1.number.dark-green 1
                .label-text
                  p Want to give back to aspiring students
                  p while making some money?
              .traveler
                h1.number.dark-green 2
                .label-text
                  p Sign up on our platform and offer your
                  p advice to interested students!
              .traveler
                h1.number.dark-green 3
                .label-text
                  p Earn money fast and get reviewed for
                  p your services. Find yourself abroad soon!
            / image
            .col-sm-7.collapsable
              = image_tag('mentors.png')
              h2.dark-green THE MENTORS

app/views/landing/_top_mentors.html.slim
- unless @top_mentors.empty?
  .preview-mentors
    hr.black
    .container
      .row
        .col-sm-offset-1.col-sm-10
          h3.dark-green Just six mentors out of hundreds!
    .sky-blue-background
      .container
        .row
          .col-sm-10.col-sm-offset-1
            .row
              - @top_mentors.each do |mentor|
                .col-sm-4.top-mentor-thumb
                  .thumbnail
                    = image_tag(mentor.user.primary_photo.small_grid.url, class: 'profile-avatar')
                    .caption
                      p.name.ellipsis = mentor.user.first_name
                      p.school.ellipsis = mentor.schools.first.university
                      p.major.ellipsis = mentor.schools.first.major
                      p.mT10.degree.ellipsis = mentor.degree.first

app/views/landing/_traveler.html.slim
.preview-traveler
  .container
    .row
      .col-sm-offset-1.col-sm-11
        h2.dark-green On the road to success.
  .container
    .row
      .col-sm-10.col-sm-offset-1
        .sky-blue-container
          .row
            / list
            .col-sm-5.mT15
              .traveler
                h1.number.dark-green 1
                .label-text
                  p Not sure if studying abroad is for you?
                  p We'll connect you with the right resources.
              .traveler
                h1.number.dark-green 2
                .label-text
                  p Get the best answers and assistance
                  p from our mentor database!
              .traveler
                h1.number.dark-green 3
                .label-text
                  p Our portal will connect you with reliable
                  p mentors. Find yourself abroad soon!
            / image
            .col-sm-7.collapsable
              = image_tag('student_traveler.png')
              h2.dark-green THE STUDENT TRAVELER

app/views/landing/index.html.slim
- cache('landing-banner') do
  / BANNER
  = render 'landing/banner'
/ TOP MENTORS
= render 'landing/top_mentors'
/ BRANDING
= render 'landing/branding'
/ TRAVELER
= render 'landing/traveler'
/ MAP
= render 'landing/map'
/ MENTORS
= render 'landing/the_mentors'
/ COMING SOON MOBILE
= render 'landing/coming_soon_mobile'
/ QUICK LINK
= render 'landing/quick_link'