config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # sidekiq web ui monitoring
  # FIXME: scope to admin user only
  require 'sidekiq/web'
  if Rails.env.production?
    authenticate :admin_user, lambda { |u| u.administrator? } do
      mount Sidekiq::Web => '/admin/sidekiq'
    end
  else
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :user, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification'
  }

  devise_scope :user do
    # student registration routes
    get 'student/register' => 'devise_extentions/student#new'
    post 'student/register' => 'devise_extentions/student#create'
    # mentor registration routes
    get 'mentor/register' => 'devise_extentions/mentor#new'
    post 'mentor/register' => 'devise_extentions/mentor#create'
  end

  resources :careers, only: [:index]
  resources :contacts, only: [:index]
  resources :dashboard, only: [:index]
  resources :landing, only: [:index]
  resources :services, only: [:index]
  resources :scholastics, only: [:index] do
    collection do
      get 'universities'
      get 'languages'
      get 'majors'
      get 'countries'
      get 'timezones'
      get 'search_tags'
    end
  end

  resources :mentors, only: [:index] do
    get 'search', on: :collection
    resources :bookmark, only: [:create, :destroy]
    member do
      post :notify_student
    end
  end

  resources :students, only: [:index] do
    get 'search', on: :collection
  end

  resources :profile, except: [:index, :destroy, :create, :new] do
    member do
      get 'mentors'
      get 'students'
      get 'account_settings'
      put 'primary_photo'
      match 'private_message', via: [:get, :post]
    end

    resources :recommendations, only: [:create]
    resources :dashboard, only: [:index]
    resources :messenger, only: [:show] do
      post :message
      get :video_call
      put :decline_video_call
    end

    resources :mentors, only: [:update] do
      put 'account_settings', on: :member
    end

    resources :students, only: [:update] do
      put 'account_settings', on: :member
    end

    resources :orders, only: [:index, :new, :create, :show] do
      member do
        put :instruction
        put :comment
        put :accept
        put :confirm
        put :in_progress
        put :completed
        put :decline
        put :cancel
        put :close
      end
    end

    resources :tasks, only: [:show, :update] do
      member do
        get :upload_request_file
        put :upload_request_file
        get :upload_revised_file
        put :upload_revised_file
        put :in_progress
        put :done
        put :completed
        put :instruction
        put :comment
        get :appointment
        put :appointment
      end

      resources :ratings
    end

    resources :appointments, except: [:destroy, :update] do
      member do
        put :decline
        put :confirm
        put :cancel
      end

      collection do
        post :request_schedule
      end
    end

    resources :schedules do
      member do
        put :close
      end

      get :checker, on: :collection
    end

    resources :images, only: [:index, :create, :destroy] do
      put :set_as_primary_photo, on: :member
    end

    resources :documents, only: [:index, :create, :destroy]
    resources :notifications, only: [:index]
    resources :transactions do
      post :hook, on: :member
    end

    resources :wallets
    resources :schools, only: [:create, :update, :destroy]
    resources :videos, only: [:create, :destroy]
    resources :alternative_contacts, only: [:create, :update, :destroy]
  end

  root 'landing#index'
end

app/models/concerns/notification_helper.rb
module NotificationHelper
  extend ActiveSupport::Concern

  def clear_notifications(user)
    notifications.where(status: Notification.pending, user: user).map(&:seen!)
  end
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id              :integer          not null, primary key
#  message         :string(255)
#  status          :string(255)      default("PENDING")
#  user_id         :integer
#  notifiable_type :string(255)
#  notifiable_id   :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  url             :string(255)
#

class Notification < ActiveRecord::Base
  STATUSES = %w(PENDING SEEN)
  include StatusHelper
  default_scope -> { order('created_at DESC') }
  scope :all_seen, -> { where(status: Notification.seen) }
  scope :all_pending, -> { where(status: Notification.pending) }
  belongs_to :notifiable, polymorphic: true
  belongs_to :user

  def seen!
    self.status = Notification.seen
    save
  end
end

app/controllers/notifications_controller.rb
# == Schema Information
#
# Table name: notifications
#
#  id              :integer          not null, primary key
#  message         :string(255)
#  status          :string(255)      default("PENDING")
#  user_id         :integer
#  notifiable_type :string(255)
#  notifiable_id   :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  url             :string(255)
#

class NotificationsController < ApplicationController
  before_filter :set_profile

  def index
    fail Pundit::NotAuthorizedError if not allowed_user?

    @notifications = @profile.pending_notifications.page(params[:page]).per(10)
  end
end

app/helpers/notifications_helper.rb
# == Schema Information
#
# Table name: notifications
#
#  id              :integer          not null, primary key
#  message         :string(255)
#  status          :string(255)      default("PENDING")
#  user_id         :integer
#  notifiable_type :string(255)
#  notifiable_id   :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  url             :string(255)
#

module NotificationsHelper
end

app/views/notifications/_notification.html.slim
.notification
  .col-sm-12.mB-20
    .pull-right
      small.darkest-gray
        span = timeago_tag(notification.created_at, :nojs => true, :limit => 10.days.ago)
  - if notification.notifiable.present?
    - if notification.user.mentor?
      / STUDENT DETAIL
      .col-sm-12
        .row
          - if notification.notifiable.present?
            .col-sm-2
              .thumbnail
                = image_tag(notification.notifiable.student.user.primary_photo.small_grid.url)
            .col-sm-10
              label
                span.mR10 Student |
                span = link_to notification.notifiable.student.user.first_name, profile_path(notification.notifiable.student.user), class: 'blue'
              p
                strong.mR10 Notification:
                span = notification.message
              - if notification.notifiable.is_a?(Order)
                / ORDER
                p
                  strong.mR10 Order Status:
                  span.blue = notification.notifiable.status.gsub('_', ' ')
                p
                  strong.mR5 Order Price:
                  span.blue = "#{notification.notifiable.currency} #{notification.notifiable.currency_symbol}#{notification.notifiable.price}"
                p
                  strong.mR10 Request Services:
                  span.blue = notification.notifiable.services.map(&:title).join(', ')
                p.mT10 = link_to t('views.orders.view_order_label'), profile_order_path(notification.notifiable.mentor.user, notification.notifiable), class: 'btn btn-default btn-sm'
              - elsif notification.notifiable.is_a?(Task)
                / TASK
                p
                  strong.mR10 Requested Service:
                  span.blue = notification.notifiable.service.title
                p
                  strong.mR10 Service Type:
                  span.blue = notification.notifiable.service.service_type.gsub('_', ' ')
                p
                  strong.mR10 Task Status:
                  span.blue = notification.notifiable.status.gsub('_', ' ')
                p.mT10 = link_to t('views.tasks.view_task_label'), profile_task_path(notification.notifiable.mentor.user, notification.notifiable), class: 'btn btn-default btn-sm'
              - elsif notification.notifiable.is_a?(Schedule)
                / SCHEDULE
                p
                  strong.mR10 Schedule Status:
                  span.blue = notification.notifiable.status.gsub('_', ' ')
                p.mT10 = link_to t('views.tasks.view_task_label'), profile_task_path(notification.notifiable.mentor.user, notification.notifiable.task), class: 'btn btn-default btn-sm'
              - elsif notification.notifiable.is_a?(Appointment)
                / APPOINTMENT
                p
                  strong.mR10 Requested Service:
                  span.blue = notification.notifiable.task.service.title
                p
                  strong.mR10 Schedule:
                  span.blue = notification.notifiable.presenter.schedule.start_datetime(@profile)
                p
                  strong.mR10 Appointment Status:
                  span.blue = notification.notifiable.status.gsub('_', ' ')
                p.mT10 = link_to t('views.tasks.view_task_label'), profile_task_path(notification.notifiable.mentor.user, notification.notifiable.task), class: 'btn btn-default btn-sm'
    - if notification.user.student?
      / MENTOR DETAIL
      .col-sm-12
        .row
          - if notification.notifiable.present?
            .col-sm-2
              .thumbnail
                = image_tag(notification.notifiable.mentor.user.primary_photo.small_grid.url)
            .col-sm-10
              label
                span.mR10 Mentor |
                span = link_to notification.notifiable.mentor.user.first_name, profile_path(notification.notifiable.mentor.user), class: 'blue'
              p
                strong.mR10 Notification:
                span = notification.message
              - if notification.notifiable.is_a?(Order)
                / ORDER
                p
                  strong.mR10 Order Status:
                  span.blue = notification.notifiable.status.gsub('_', ' ')
                p
                  strong.mR5 Order Price:
                  span.blue = "#{notification.notifiable.currency} #{notification.notifiable.currency_symbol}#{notification.notifiable.price}"
                p.mT10 = link_to t('views.orders.view_order_label'), profile_order_path(notification.notifiable.student.user, notification.notifiable), class: 'btn btn-default btn-sm'
              - elsif notification.notifiable.is_a?(Task)
                / TASK
                p
                  strong.mR10 Requested Service:
                  span.blue = notification.notifiable.service.title
                p
                  strong.mR10 Service Type:
                  span.blue = notification.notifiable.service.service_type.gsub('_', ' ')
                p
                  strong.mR10 Task Status:
                  span.blue = notification.notifiable.status.gsub('_', ' ')
                p.mT10 = link_to t('views.tasks.view_task_label'), profile_task_path(notification.notifiable.student.user, notification.notifiable), class: 'btn btn-default btn-sm'
              - elsif notification.notifiable.is_a?(Schedule)
                / SCHEDULE
                p
                  strong.mR10 Schedule Status:
                  span.blue = notification.notifiable.status.gsub('_', ' ')
                p.mT10 = link_to t('views.tasks.view_task_label'), profile_task_path(notification.notifiable.student.user, notification.notifiable.task), class: 'btn btn-default btn-sm'
              - elsif notification.notifiable.is_a?(Appointment)
                / APPOINTMENT
                p
                  strong.mR10 Requested Service:
                  span.blue = notification.notifiable.task.service.title
                p
                  strong.mR10 Schedule:
                  span.blue = notification.notifiable.presenter.schedule.start_datetime(@profile)
                p
                  strong.mR10 Appointment Status:
                  span.blue = notification.notifiable.status.gsub('_', ' ')
                p.mT10 = link_to t('views.tasks.view_task_label'), profile_task_path(notification.notifiable.student.user, notification.notifiable.task), class: 'btn btn-default btn-sm'
  - else
    .col-sm-12
      .row
        .col-sm-2
        .col-sm-10
          p
            strong.mR10 Notification:
            span = notification.message
          p.mT10 = link_to t('views.tasks.view_task_label'), notification.url, class: 'btn btn-default btn-sm'
  .row
    .col-sm-12
      hr.blue

app/views/notifications/index.html.slim
.container
  .profile.mT20
    .row
      = render 'profile/profile_sidebar'
      .col-sm-9
        .box-panel.box-gray
          .box-inner
            .row
              .col-sm-12
                h2.mB10
                  span.mR10.blue Pending Notifications
                  span = "(#{@profile.pending_notifications.size})"
              .col-sm-12
                hr.blue
                #notifications.row
                  - if @notifications.empty?
                    p.text-center.text-danger No Pending Notifications.
                  - else
                    = render @notifications, cache: true
                .row
                  .col-sm-12
                    .text-center
                      = paginate @notifications