config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # sidekiq web ui monitoring
  # FIXME: scope to admin user only
  require 'sidekiq/web'
  if Rails.env.production?
    authenticate :admin_user, lambda { |u| u.administrator? } do
      mount Sidekiq::Web => '/admin/sidekiq'
    end
  else
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :user, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification'
  }

  devise_scope :user do
    # student registration routes
    get 'student/register' => 'devise_extentions/student#new'
    post 'student/register' => 'devise_extentions/student#create'
    # mentor registration routes
    get 'mentor/register' => 'devise_extentions/mentor#new'
    post 'mentor/register' => 'devise_extentions/mentor#create'
  end

  resources :careers, only: [:index]
  resources :contacts, only: [:index]
  resources :dashboard, only: [:index]
  resources :landing, only: [:index]
  resources :services, only: [:index]
  resources :scholastics, only: [:index] do
    collection do
      get 'universities'
      get 'languages'
      get 'majors'
      get 'countries'
      get 'timezones'
      get 'search_tags'
    end
  end

  resources :mentors, only: [:index] do
    get 'search', on: :collection
    resources :bookmark, only: [:create, :destroy]
    member do
      post :notify_student
    end
  end

  resources :students, only: [:index] do
    get 'search', on: :collection
  end

  resources :profile, except: [:index, :destroy, :create, :new] do
    member do
      get 'mentors'
      get 'students'
      get 'account_settings'
      put 'primary_photo'
      match 'private_message', via: [:get, :post]
    end

    resources :recommendations, only: [:create]
    resources :dashboard, only: [:index]
    resources :messenger, only: [:show] do
      post :message
      get :video_call
      put :decline_video_call
    end

    resources :mentors, only: [:update] do
      put 'account_settings', on: :member
    end

    resources :students, only: [:update] do
      put 'account_settings', on: :member
    end

    resources :orders, only: [:index, :new, :create, :show] do
      member do
        put :instruction
        put :comment
        put :accept
        put :confirm
        put :in_progress
        put :completed
        put :decline
        put :cancel
        put :close
      end
    end

    resources :tasks, only: [:show, :update] do
      member do
        get :upload_request_file
        put :upload_request_file
        get :upload_revised_file
        put :upload_revised_file
        put :in_progress
        put :done
        put :completed
        put :instruction
        put :comment
        get :appointment
        put :appointment
      end

      resources :ratings
    end

    resources :appointments, except: [:destroy, :update] do
      member do
        put :decline
        put :confirm
        put :cancel
      end

      collection do
        post :request_schedule
      end
    end

    resources :schedules do
      member do
        put :close
      end

      get :checker, on: :collection
    end

    resources :images, only: [:index, :create, :destroy] do
      put :set_as_primary_photo, on: :member
    end

    resources :documents, only: [:index, :create, :destroy]
    resources :notifications, only: [:index]
    resources :transactions do
      post :hook, on: :member
    end

    resources :wallets
    resources :schools, only: [:create, :update, :destroy]
    resources :videos, only: [:create, :destroy]
    resources :alternative_contacts, only: [:create, :update, :destroy]
  end

  root 'landing#index'
end

app/views/shared/_branding_header.html.slim
- cache('branding-heading') do
  .main-header
    .container.mT10
      .pull-right
        ul.nav.navbar-nav.mR10
            li
              = link_to 'https://www.facebook.com/afriendabroad', target: '_blank', title: 'Visit our facebook page', class: 'p5 menu-link' do
                = image_tag('facebook.png')
            li
              = link_to 'https://twitter.com/Afriendabroad', target: '_blank', title: 'Visit our twitter page', class: 'p5 menu-link mR20' do
                = image_tag('twitter.png')
            li
              = link_to '', class: 'btn btn-theme btn-nav', title: 'Login', data: { toggle: 'modal', target: '#login-modal'} do
                span.header-label LOGIN
    .container
      .navbar-custom-menu
        ul.nav.navbar-nav.logo-holder
          li
            = link_to root_path
              = image_tag('logo.png', class: 'logo')
        ul.nav.navbar-nav.main-menu
          li
            = link_to root_path, title: 'Home', class: 'menu-link' do
              span.header-label.mL5 Home
          li
            = link_to services_path, title: 'Services', class: 'menu-link' do
              span.header-label.mL5 Services
          li
            = link_to mentors_path, title: 'Mentors', class: 'menu-link' do
              span.header-label.mL5 Mentors
          li
            = link_to students_path, title: 'Students', class: 'menu-link' do
              span.header-label.mL5 Students
          li
            = link_to 'mailto:admin@afriendabroad.com', title: 'Contact', class: 'menu-link' do
              span.header-label.mL5 Contact
    hr

app/views/shared/_flash.html.slim
- flash.delete(:timedout).each do |k, v|
  .alert.alert-dismissible class="alert-#{k} mT10" role='alert'
    button.close type='button' data-dismiss='alert' aria-label='Close'
      span aria-hidden='true' &times;
    = v

app/views/shared/_footer.html.slim
- cache('footer') do
  .container
    .row
      .col-sm-10.col-sm-offset-1.mT20
        = link_to root_path
          = image_tag('branding.png')
        = link_to root_path, class: 'm30'
          = image_tag('danish-logo.png')
      .col-sm-10.col-sm-offset-1.mB20
        .text-center
          = link_to 'SUPPORT', 'mailto:admin@afriendabroad.com', title: 'SUPPORT', class: 'menu-link'
          span.m5.blue •
          = link_to 'CAREERS', careers_path, title: 'CAREERS', class: 'menu-link'
          span.m5.blue •
          = link_to 'FAQ', '#', title: 'FAQ', class: 'menu-link'
          span.m5.blue •
          = link_to 'CONTACT US', contacts_path, title: 'CONTACT US', class: 'menu-link'

app/views/shared/_header.html.slim
.main-header
  .container.mT10
    - if current_user.administrator?
      .pull-left.admin_panel
        .btn-group.mT20
          = link_to 'Go Back To Admin Panel', admin_root_path, class: 'btn btn-info'
          = link_to 'Login as a normal user', new_user_session_path, class: 'btn btn-primary'
    .pull-right
      ul.nav.navbar-nav.mR10
          - if current_user.administrator?
            li
              = link_to profile_orders_path(@profile), title: 'Orders', class: 'btn btn-theme btn-nav' do
                span.ion-android-document
            li
              = link_to profile_notifications_path(@profile), title: 'Notifications', class: 'btn btn-theme btn-nav', id: 'notification-count-container' do
                span.ion-person-stalker
                span#count #{pending_notification_presenter(@profile.pending_notifications.size)}
            li
              = link_to '#', title: 'Message', class: 'btn btn-theme btn-nav' do
                span.ion-ios-email
            li
              = link_to account_settings_profile_path(@profile), title: 'Setttings', class: 'btn btn-theme btn-nav' do
                span.ion-ios-gear
          - else
            li
              = link_to profile_orders_path(current_user), title: 'Orders', class: 'btn btn-theme btn-nav' do
                span.ion-android-document
            li
              = link_to profile_notifications_path(current_user), title: 'Notifications', class: 'btn btn-theme btn-nav', id: 'notification-count-container' do
                span.ion-person-stalker
                span#count #{pending_notification_presenter(current_user.pending_notifications.size)}
            li
              = link_to '#', title: 'Message', class: 'btn btn-theme btn-nav' do
                span.ion-ios-email
            li
              = link_to account_settings_profile_path(current_user), title: 'Setttings', class: 'btn btn-theme btn-nav' do
                span.ion-ios-gear
          li
            = link_to destroy_user_session_path, class: 'btn btn-theme btn-nav', title: 'Sign out' do
              span.header-label LOGOUT

  .container
    .navbar-custom-menu.application-header
      - unless current_user.administrator?
        ul.nav.navbar-nav.user-identity
          li.avatar
            .profile-avatar
              .preview
               = image_tag(current_user.primary_photo.small_grid.url)
          li.user-name
            = link_to profile_path(current_user)
              span= current_user.first_name
      - if current_user.administrator?
        ul.nav.navbar-nav.main-menu
          li
            = link_to profile_path(@profile), title: 'My Profile', class: 'menu-link' do
              span.header-label.mL10 My Profile
          - if @profile.student?
            li
              = link_to profile_schedules_path(@profile), title: 'Schedule', class: 'menu-link' do
                span.header-label.mL10 Schedule
          - if @profile.mentor?
            li
              = link_to profile_appointments_path(@profile), title: 'Appointments', class: 'menu-link' do
                span.header-label.mL10 Appointments
            li
              = link_to students_path, title: 'Students', class: 'menu-link' do
                  span.header-label.mL10 Students
          - if @profile.student?
            li
              = link_to mentors_path, title: 'Search', class: 'menu-link' do
                span.header-label.mL10 Search
      - else
        ul.nav.navbar-nav.main-menu
          li
            = link_to profile_path(current_user), title: 'My Profile', class: 'menu-link' do
              span.header-label.mL10 My Profile
          - if current_user.student?
            li
              = link_to profile_schedules_path(current_user), title: 'Schedule', class: 'menu-link' do
                span.header-label.mL10 Schedules
          - if current_user.mentor?
            li
              = link_to profile_appointments_path(current_user), title: 'Appointments', class: 'menu-link' do
                span.header-label.mL10 Appointments
            li
              = link_to students_path, title: 'Students', class: 'menu-link' do
                  span.header-label.mL10 Students
          - if current_user.student?
            li
              = link_to mentors_path, title: 'Search', class: 'menu-link' do
                span.header-label.mL10 Search
  hr

app/views/shared/_loader.html.slim
.loader
  .inner-loader.blue
    h1.spinner.ion-load-a.rotate
    p Please wait ...

app/views/shared/_sharer.html.slim
- cache('sharer') do
  .social-buttons
    ul.links
      li
        = link_to '#', class: 'social-share facebook', data: { url: root_url, type: 'facebook', description: t('views.social_media.description') } do
          span.ion-social-facebook
      li
        = link_to '#', class: 'social-share twitter', data: { url: root_url, via: 'Afriendabroad', type: 'twitter', description: t('views.social_media.description') } do
          span.ion-social-twitter
      li
        = link_to '#', class: 'social-share googleplus', data: { url: root_url, type: 'googleplus', description: t('views.social_media.description') } do
          span.ion-social-googleplus
      li
        = link_to '#', class: 'social-share linkedin', data: { url: root_url, via: 'Afriendabroad', type: 'linkedin', description: t('views.social_media.description') } do
          span.ion-social-linkedin